### ISSUE TITLE
'CEF' folder inside NuGet package, despite 'lib' as standard.

### ISSUE THREAD

**Issue by devBartek** [cefsharp/cef-binary#101]
Hi.

Is there any reason, that you publish dll's in ```CEF``` folder inside NuGet package?
https://github.com/cefsharp/cef-binary/blob/e332392d0c47f671ec07e92c0948d07a8abc8b70/NuGet/cef.redist.nuspec#L18

If I'm not wrong, ``lib`` folder is standard for this.
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-convention-based-working-directory

**Comment by amaitland** [comment]
The files inside the CEF folder are unmanaged dlls and resources, they are also arch specific.  Lib folder is for managed assemblies (Lib folder doesn't support arch specific dlls also).

**Comment by amaitland** [comment]
The newer chromiumembeddedframework.runtime packages will hopefully replace the Older cef.redist packages. 

https://github.com/cefsharp/cef-binary/blob/master/NuGet/chromiumembeddedframework.runtime.win.nuspec#L25

#93
