### ISSUE TITLE
Adding cefsharp to the project adds both x64 and x86

### ISSUE THREAD

**Issue by senbagaraman04** [cefsharp/cef-binary#102]
Is it intended that while adding the cefsharp both the versions got created. and it can be visible in the output folder also. These files are making the release folder little heavy.

**Comment by amaitland** [comment]
Please ask CefSharp questions on https://github.com/cefsharp/CefSharp/discussions

Making sure to include more detail as it's not clear what you are referring to here, targeting AnyCPU including both is expected.
