### ISSUE TITLE
cef.redist.x64 and cefredist.x86 missing version > 120.2.7 on Nuget

### ISSUE THREAD

**Issue by SimonMagnet** [cefsharp/cef-binary#112]
There are no version 121 of cef.redist.x64 and cefredist.x86.
Were they forgotten? or is there another reason?

https://www.nuget.org/packages/cef.redist.x86
https://www.nuget.org/packages/cef.redist.x64

**Comment by amaitland** [comment]
Those packages are no longer being maintained. 

See https://github.com/cefsharp/cef-binary/issues/93#issuecomment-1925562698
