### ISSUE TITLE
How to build libcef_dll_wrapper.lib for Version 37 using VS2010

### ISSUE THREAD

**Issue by rover886** [cefsharp/cef-binary#26]
Hi team,

   I want to build `libcef_dll_wrapper.lib` for `Visual studio 2010` for latest (v37) cefsharp.To do this I have downloaded cef-binary-master.zip from https://github.com/cefsharp/cef-binary. changed `build.ps1` as suggested by @jornh @ https://github.com/cefsharp/CefSharp/issues/810#issuecomment-74373732 but I am not able to run `build.ps1` file getting error 

Copy-Item : Cannot find path 'E:\Downloads\cef-binary-master_V37\cef-binary-master\cef_binary_3.y.z_windows64\include'
because it does not exist.
At E:\Downloads\cef-binary-master_V37\cef-binary-master\build.ps1:117 char:12
+   Copy-Item <<<<  $Cef64\include $CefInclude -Recurse | Out-Null
    + CategoryInfo          : ObjectNotFound: (E:\Downloads\ce...ndows64\include:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

After checking path `E:\Downloads\cef-binary-master_V37\cef-binary-master\cef_binary_3.y.z_windows64\` i found that only `.empty` file is there. SO how can i download

**Comment by amaitland** [comment]
You'll need to download the `x64` and `x86` versions from http://cefbuilds.com/#branch_2062

Unzip and copy into their relevant folders.

**Comment by rover886** [comment]
Okay, thanks I started downloading. Just for knowledge how you decide which branch need to download. I mean How you decided to download branch 2062 whereas more other version are available on that website.

**Comment by amaitland** [comment]
If you look closer you'll see that `2062` builds say something like `Chromium 37.0.2062.94`, which means it's version 37. The `master` branch is setup to build versions for `39`, so you'll have to look back through the history and pick the last `37` version.

**Comment by rover886** [comment]
Thanks a lot.

**Comment by rover886** [comment]
I tried as you said, after downloading and extracting `cef-binary-master.zip` which is having blank `cef_binary_3.y.z_windows64` and `cef_binary_3.y.z_windows32` folders I downloaded `cef_binary_3.2062.1930_windows32` and `cef_binary_3.2062.1930_windows64` and extracted all its content to there respective folder.

Then I modified `build.ps1` as 

    switch -Exact ($Target) {
    "nupkg" {
        #VSX v120
        #VSX v110
        VSX v100
        Nupkg
    }
	"nupkg-only" {
        Nupkg
    }
    "vs2013" {
        VSX v120
    }
    "vs2012" {
        VSX v110
    }
    "vs2010" {
        VSX v100
    }
    }

After running this file from power shell I got this message:
```
    206 Warning(s)
    103 Error(s)

    Time Elapsed 00:00:27.55

    Die : Build failed
At E:\Downloads\cef-binary-master_V37\cef-binary-master\build.ps1:240 char:12
+         Die <<<<  "Build failed"
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Die
```
There are so many errors on power shell window, don't know which to post. I also tried by opening `cefclient2010.sln` (32 bit) in `VS2010` and build the solution but got error as `error C2220: warning treated as error - no 'object' file generated`. Where I am doing wrong?

**Comment by amaitland** [comment]
`master` = `2171`, you'll need to go through the commit history and find the last `2062` commit.

**Comment by rover886** [comment]
okay, is this https://github.com/cefsharp/cef-binary/tree/2e18189fc4deaa5c70069fb5402a101371a8e4f4 is the last commit on `2062`, just confirm please?

**Comment by amaitland** [comment]
Yep, that's it.

**Comment by rover886** [comment]
I tried with downloading `cefsharp-cefbinary` for `2062` version. and executed build.ps1. This time also it got ended with error :cry: 

```
    206 Warning(s)
    103 Error(s)

Time Elapsed 00:00:31.06

Die : Build failed
At E:\Downloads\cef-binary-37\cef-binary-37\build.ps1:298 char:12
+         Die <<<<  "Build failed"
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Die
```
I observed first occurrence of error and warning it's as below

```
D:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\typeinfo(157): error C2220: warning treated as error - n
o 'object' file generated [E:\Downloads\cef-binary-37\cef-binary-37\cef_binary_3.y.z_windows32\libcef_dll_wrapper.vcxpr
oj]
D:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\typeinfo(157): error C2220: warning treated as error - n
o 'object' file generated [E:\Downloads\cef-binary-37\cef-binary-37\cef_binary_3.y.z_windows32\libcef_dll_wrapper.vcxpr
oj]
D:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\typeinfo(157): warning C4275: non dll-interface class 's
tdext::exception' used as base for dll-interface class 'std::bad_cast' [E:\Downloads\cef-binary-37\cef-binary-37\cef_bi
nary_3.y.z_windows32\libcef_dll_wrapper.vcxproj]
          D:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\exception(218) : see declaration of 'stdext::e
  xception'
          D:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\typeinfo(156) : see declaration of 'std::bad_c
  ast'

```

**Comment by amaitland** [comment]
@rover886 Did you sort this? Can we close? From other comments it sounds like you got things working.
