### ISSUE TITLE
Upgrade to 2171.2069

### ISSUE THREAD

**Issue by amaitland** [cefsharp/cef-binary#27]
Housekeeping for upgrading to `2171.2069`

Update `build.ps1` to reflect version bump
https://github.com/cefsharp/cef-binary/blob/master/build.ps1#L18
Import latest `README.txt` from `Cef`
https://github.com/cefsharp/cef-binary/blob/master/README.txt

**Comment by amaitland** [comment]
@rassilon Though this might be a better place to discuss upgrade of `2171.2069`.

Do you have a `MyGet` account? You can push the new packages to the `MyGet` feed when your happy.

**Comment by amaitland** [comment]
@rassilon Moving discussion here

> 2171 based on CEF's branch web page ONLY supports VS2013 Update 4 or later.
> Based on this, does it make any sense to use build.ps1 for VS2012?

Whilst `Cef` requires `VS2013 Update 4` to build we still need to build `libcef_dll_wrapper` for `VS2012` as the official `CefSharp` packages are build against `VC++ 2012`.

**Comment by rassilon** [comment]
I do now. :smile:  Same username on myget as here.

**Comment by amaitland** [comment]
> I do now. :smile: Same username on myget as here.

You should have access now :smile:

**Comment by rassilon** [comment]
Ok, I've pushed to MyGet and here. Check it out. the build.ps1 changes ought to work pre-2171.2069 as well.

**Comment by rassilon** [comment]
Do you think we should move to only VC++ 2013 with 2272? Or sometime later? I might be able to push a 2272 to MyGet tonight.

**Comment by amaitland** [comment]
That's a tough one. I think you'll find community resistance when updating to anything newer. Feel free to open the question to a wider audience.

**Comment by amaitland** [comment]
Personally, I'm fine with moving on.

**Comment by amaitland** [comment]
The `Community Edition` of Visual Studio may make this less of a problem now than it was before.

**Comment by peters** [comment]
+1 for upgrading! Bundling the redist files with their app is what most
people are doing anyway.

On Thursday, March 26, 2015, Alex Maitland <notifications@github.com> wrote:

> The Community Edition of Visual Studio may make this less of a problem
> now than it was before.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cefsharp/cef-binary/issues/27#issuecomment-86291178>.
>


-- 
Regards,
Peter Sunde.

**Comment by amaitland** [comment]
I've tried updating to `2069` and I'm getting multiple link errors, one example is

```
Error 112	error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in AssemblyInfo.obj	C:\projects\github\CefSharp\CefSharp.Core\libcef_dll_wrapper.lib(post_data_element_ctocpp.obj)
```

I pushed the changes to https://github.com/amaitland/CefSharp/commits/cef/2171.2069

**Comment by amaitland** [comment]
`Nuget.config` example.

```
<packageSources>
	<add key="nuget.org" value="https://nuget.org/api/v2/" /> 
	<add key="cefsharp-local" value="C:\projects\cef-binary\NuGet" />	
</packageSources>
```

**Comment by rassilon** [comment]
I'll check it out. 

Bill

**Comment by rassilon** [comment]
Oh, I bet I know what happened, the reordering I discovered needed to be done in build.ps1 while I was doing 2272 meant the wrong CRT got built against the 2171 build I had. I'll see if I can fix that.

**Comment by rassilon** [comment]
Ok, I've updated the 2171 pkg on MyGet and your changes build fine now using those packages. Don't forget to delete the packages from your solution packages directory and the AppData\Local\NuGet\Cache directory.

Bill

**Comment by amaitland** [comment]
Appears to be working now :+1: I've tested with `VS2012`, `Release`, `Debug`, `x86` and `x64` variations and everything appears to be ok on the surface.

**Comment by amaitland** [comment]
I've merged the changes into `master`. Will hold off a few days before pushing the packages to `Nuget.org`, hopefully people will have time to take it for a spin.

**Comment by rassilon** [comment]
I saw you pushed the cef-binary redist pkgs to nuget, but -pre03 still uses the older NuGet pkg version. Were you going to push a -pre04, or hoping to just push 39.0?

**Comment by amaitland** [comment]
Prefer to release 39, thought that seems to be a moving target at the moment. Looking at the list I think some can be deferred to a point release. So I'll probably pull the trigger on 39 in the next few days. Thoughts?

Looks like cefbuilds is at least partly up and running again.
