### ISSUE TITLE
2272 branch

### ISSUE THREAD

**Issue by rassilon** [cefsharp/cef-binary#28]
I've pushed NuGet pkgs to MyGet for 2272.25 (.25 is a bitbucket GIT only build number after the move away from Google code).

Fyi,
Bill

**Comment by odalet** [comment]
Hi, I don't understand why nuget packages exist both on nuget and myget: myget packages provide more recent versions but nuget packages are younger (hence, I can't update from nuget's version to myget's one using Visual Studio...). Could-you explain what feed I should use for what purpose?
Thanks!

**Comment by amaitland** [comment]
Official releases go onto `nuget.org`. `CI builds` and experimental versions are on `MyGet`.

`2171` = `Chromium 39`
`2272` = `Chromium 41`.

Typically we repackage `CEF` using releases from https://cefbuilds.com/

If you look there you'll see the different branches, which match the `Chromium` branches.

In general, your average person should use `Nuget.org`.

@rassilon It looks like `cefbuilds.com` is back in action. They appear to be using the old style numbering. Happy just to follow that going forward?

**Comment by rassilon** [comment]
@amaitland , They did use the old style numbering for 2171 (which isn't surprising, there haven't been any other additional commits on that branch that are CEF code related, only CEF build related ).

The only difference between cefbuilds.com's 2272 build and the one I did on MyGet is:

    Update to Chromium version 41.0.2272.104

As you can see they've switched to the new build numbers for trunk. (they have the git treeid suffix)
The MyGet pkg I uploaded didn't bother including the git treeid suffix in the pkg details.

So, for 2171 we can totally use the cefbuilds.com bits if we want, ditto for 2272 if we so desire.

Bill

**Comment by amaitland** [comment]
Looks like `cefbuilds.com` is only working on the surface. When I downloaded the latest `2272` packages it appears to be pointing to https://bitbucket.org/chromiumembedded/branches-2272-cef3/ which is out of date.

Looks like `trunk` is working, so hopefully `2272` gets updated sometime soon.

**Comment by amaitland** [comment]
@rassilon Do you still have a build environment setup? Think you'd be able to build the latest `2272`. `cefbuilds.com` is still broken for basically everything except `trunk`.

**Comment by rassilon** [comment]
Yeah, I could try kicking a build off tonight. The work is mostly automated, it just takes forever....

**Comment by amaitland** [comment]
Cool, thanks :smile:

**Comment by rassilon** [comment]
The 2357 branch just got created, btw.

**Comment by amaitland** [comment]
Thanks for the heads up :+1: I had read comments from `Marshall` saying it was likely to happen this month.

**Comment by rassilon** [comment]
The build finished fine, I'll see if I can't push some cef-binary magic to MyGet tomorrow night.

**Comment by amaitland** [comment]
> The build finished fine, I'll see if I can't push some cef-binary magic to MyGet tomorrow night.

Awesome, thanks :+1:

**Comment by odalet** [comment]
@amaitland Late in seeing your answer (had other occupation); anyway thanks, that clarifies things.

**Comment by rassilon** [comment]
Oh bother, I forgot to kick off the x64 build. building now fyi.

**Comment by amaitland** [comment]
Two commits in the last 24hrs to `2272`, `IME` related. Worth including those do you think?

**Comment by rassilon** [comment]
I've pushed 2272.30 to MyGet. (which would include the IME stuff) I managed to push x64 symbols for cef.redist, but the x86 symbols haven't been able to push out yet. (It's ~234MB) 

The tiny complication of course is that cef.sdk is a static library so if we want to publish symbols for that, they'd need to be part of CefSharp.Common's symbol package. (which means pushing the libcef_dll CEF source with CefSharp.Common)

Fyi,
Bill

**Comment by amaitland** [comment]
> I managed to push x64 symbols for cef.redist, but the x86 symbols haven't been able to push out yet. (It's ~234MB)

I downloaded and unzipped both packages from the `MyGet` feed, what exactly is different? Slightly confused here! lol

**Comment by rassilon** [comment]
Symbols get published to symbolsource.org and not MyGet. The pkg name ends up being: cef.redist.x86.symbols.3.2272.30.nupkg

**Comment by amaitland** [comment]
> Symbols get published to symbolsource.org and not MyGet

Totally clear now, very cool :+1: Guess I'd only considered publishing the `CefSharp` symbols as the `CEF` ones are so large.

**Comment by rassilon** [comment]
No kidding... 1GB uncompressed. Painful.

**Comment by amaitland** [comment]
Would you happen to have the `2171` symbols still lying around? Request on the google group.

https://groups.google.com/forum/#!topic/cefsharp/k0DRwr4k7VA

**Comment by rassilon** [comment]
Hrm. Maybe. I'll look at home.

**Comment by amaitland** [comment]
> Hrm. Maybe. I'll look at home.

Thanks.

**Comment by rassilon** [comment]
No such luck. I'm going to try and build it again.

**Comment by amaitland** [comment]
> No such luck. I'm going to try and build it again.

:frowning: 

I've just updated the `2272` branch to use `2272.30`, few API changes, the `OnBeforeResourceLoad` probably needs to be revisited as there is now an async callback. The methods are now using a generic `CefRequestCallback` handler now, so at least if we wrapped them there's not a different type for each one. Probably should put that on the list.

**Comment by amaitland** [comment]
@rassilon Are you happy if I remove the old `2272.25` packages from `MyGet`?

**Comment by rassilon** [comment]
Go for it.

**Comment by rassilon** [comment]
Btw, I'm in the process of compressing some .pdbs to distribute the 2171 symbols. I have a OneDrive account that can actually store some symbols now.

**Comment by amaitland** [comment]
How'd the upload to `symbolsource.org` go?

**Comment by rassilon** [comment]
I tried several times, but they never went through. :frowning: 

Bill

**Comment by amaitland** [comment]
Bugger, maybe there's just too big?

**Comment by amaitland** [comment]
Wonder if it's possible to push them onto `GitHub` directly, when you create a `Release` it's possible to upload binary files. Might be worth a go at uploading them to the `cef-binary` project?

**Comment by rassilon** [comment]
Interesting. I can give it a shot.

**Comment by rassilon** [comment]
Hrm, had any thoughts about skipping 2272 and going straight to 2357?

Bill

**Comment by amaitland** [comment]
Last time I checked the `2357` branch had been created though `Chrome 43` wasn't released, so hadn't considered it. Looks like that changed a couple of days ago.

It might be worth skipping `2272`, the next official release is still likely a couple of months away, so `CEF` should have stabilized by then. I'd usually wait until `CEF` upgrades to the second `Chromium` revision in a branch, which seems to take about a month.

**Comment by amaitland** [comment]
I do like the fact that `cefbuilds` is producing `2357` builds, so users can download the relevant `cefclient` and `symbols` packages.

**Comment by rassilon** [comment]
Check out the draft release I just did in cef-binary. If you like it, feel free to click the button.

**Comment by amaitland** [comment]
For clarity `CEF 3.0.2171.69` = `3.2171.2069` or is `69` the new `git` revision? In which case the symbols prob don't match (`API` has changed).

**Comment by rassilon** [comment]
Just me fat fingering the version number. I've fixed the draft.

**Comment by amaitland** [comment]
I tweaked the file names, and description. Thanks for taking the time to build those :+1: 

It's included a tag, for the `cef-binary` project, which really isn't a big deal, so we can just ignore that for now.

**Comment by amaitland** [comment]
Looks like `2357` now has `Two way SSL support` as of 14 hours ago, I know a few people have been looking for that.

**Comment by amaitland** [comment]
If we're going to switch to `2357` then I think now is the time. By the time we get `2272` stabalised, it'll probably be time to upgrade, so I'm ok with skipping `2272`.

I'll look at updating next week if nobody gets in before me.

**Comment by rassilon** [comment]
Sounds good. Think we can use cefbuilds. com?

**Comment by amaitland** [comment]
> Think we can use cefbuilds. com?

I really hope so, new build pushed the other day. One way to find out :smile:

**Comment by amaitland** [comment]
`2357` has been upgraded to `Chromium version 43.0.2357.81`, so hopefully a new build will appear shortly.

**Comment by amaitland** [comment]
Looks like the builds will be available  in the next day or two.

The problem may well be `PDF` support appears to be lacking somewhat.

https://bitbucket.org/chromiumembedded/cef/issue/1565
http://magpcss.org/ceforum/viewtopic.php?f=6&t=13065&sid=f3b1789990c5bde0fc9b5d717dfac671

**Comment by amaitland** [comment]
So I'm thinking a slightly revised plan of action might be the go. Grab `CEF 3.2272.32` from `cefbuilds.com`, produce a new set of packages. Merge the handful of changes into `master` required be compatible with `2272`, release a `-pre` version. If all goes well release `41.0.0` in two weeks. Should be a fairly low risk upgrade.

Move the `2272` work onto `2357`, even with it's lacking `PDF` support. `cefbuilds.com` is still slightly out of whack with the `2357` branch. Might use the slightly older `CEF 3.2357.1274` version in the short term, just pushing the packages to `myget.org`, nothing official to `Nuget.org` until we're ready for a release. Will see how long step 1 of this plan takes, it may sync up again before then.

**Comment by rassilon** [comment]
That sounds OK to me. I could try and build the tip of 2357 this week at home and push to myget/cef-binary as we. Some of the recent changes on 2357 fix some missing features our users have been asking for.

**Comment by amaitland** [comment]
> I could try and build the tip of 2357 this week at home and push to myget/cef-binary

Up to you. I think for an official release it would be ideal to use the `cefbuilds.com` version as you can download symbols and a working `cefclient` build. On the surface it looks like the `32bit` version is up to date.. So maybe we can just get away with building the `64bit` version?

**Comment by amaitland** [comment]
`32bit` build of `Chromium 43.0.2357.130` appeared on `cefbuilds.com` today, so hopefully the `64bit` will follow in the next `24hrs` and I can build a new set of packages :smile:

**Comment by jankurianski** [comment]
> 32bit build of Chromium 43.0.2357.130 appeared on cefbuilds.com today, so hopefully the 64bit will follow in the next 24hrs and I can build a new set of packages

Unfortunately the 64bit build is still not out, and I've got an interest in getting `43` to work because it fixes a bug where the mouse cursor is broken in virtual machines (https://code.google.com/p/chromium/issues/detail?id=456222#c178).

Since `3.2357.1274` is the last version with both 32-bit and 64-bit builds, I tried to get that working.

`cef-binary` did need one important change; the inclusion of 2 `.bin` files to the distribution:
https://github.com/cefsharp/cef-binary/compare/master...NumbersInternational:cef/2357-jan?expand=1

`CefSharp` had some simple changes due to signatures.  One important fix was removing `delete this` in `ResourceHandlerWrapper.cpp` to avoid an access violation:
https://github.com/cefsharp/CefSharp/compare/master...NumbersInternational:cef/2357-jan?expand=1

The net result is that all of the Example projects (`OffScreen`, `WinForms` and `WPF`) are working.

Not sure what stage you guys are at - is this a worthwhile PR or would you prefer to wait for a newer build?

**Comment by amaitland** [comment]
The `64bit` build is failing at the moment, the relevant issue is https://bitbucket.org/chromiumembedded/cef/issues/1647/conversion-from-size_t-to-int-possible. I've submitted a `PR`, still waiting to hear back. It's a trivial error. 

> Not sure what stage you guys are at - is this a worthwhile PR or would you prefer to wait for a newer build?

Do you have a `MyGet` account? I can grant you access to push the `cef.redist/sdk` packages. I was waiting for a newer version, though if you've already packaged and older one then I'm happy to see it merged :+1:

**Comment by jankurianski** [comment]
> Do you have a MyGet account? I can grant you access to push the cef.redist/sdk packages. I was waiting for a newer version, though if you've already packaged and older one then I'm happy to see it merged

Sounds good.  My MyGet username is `jankurianski`

**Comment by jankurianski** [comment]
> The 64bit build is failing at the moment, the relevant issue is https://bitbucket.org/chromiumembedded/cef/issues/1647/conversion-from-size_t-to-int-possible. I've submitted a PR, still waiting to hear back. It's a trivial error.

Awesome, good work for chasing that down :+1:

**Comment by amaitland** [comment]
> Sounds good. My MyGet username is jankurianski

You should now have access to the `https://www.myget.org/F/cefsharp/` feed.

**Comment by jankurianski** [comment]
> You should now have access to the https://www.myget.org/F/cefsharp/ feed.

I do, thanks.  Though the `cef.redist` / `cef.sdk` packages are not shown in `nuget list`, I assume that I'm doing the right thing by doing something like this: `nuget push cef.sdk.3.2357.1274.nupkg -source https://www.myget.org/F/cefsharp/`?

**Comment by amaitland** [comment]
You probably need to specify the `API Key`, which should be available from `Feed Details`.

**Comment by amaitland** [comment]
Looks like the `64bit` build problem should soon be resolved as the fix has been applied to `2357` and `master`. 

Soon as a newer `2357` build is out I'd like to upgrade again :smile:

**Comment by jankurianski** [comment]
Definitely!  I'm happy to do the build and upload again, it was pretty easy thanks to good instructions.

**Comment by amaitland** [comment]
Just as point of interest there is now a `2454` branch.

https://bitbucket.org/chromiumembedded/cef/branch/2454

**Comment by jankurianski** [comment]
There are now `x86` and `x64` builds of the same CEF version, `3.2357.1287.g861c26e`.  I'll package them up today.

**Comment by amaitland** [comment]
Fantastic :+1:

**Comment by jankurianski** [comment]
I have updated the MyGet `cef.*` packages, but having trouble running the `CefSharp` examples (`FileLoadException`, `A procedure imported by 'CefSharp.Core.dll' could not be loaded.`).  Will keep working on it tomorrow.  Perhaps related to me building on Windows 10 :confused:

**Comment by amaitland** [comment]
> Perhaps related to me building on Windows 10 :confused:

What version of `VS` are you using? If it's `VS2015` do you also have `VS2013` installed?

I just ran the nuget upgrade and everything went fine for me locally.

**Comment by amaitland** [comment]
https://github.com/amaitland/CefSharp/commit/00cc4fa395f067c8a9bfbd0e029ec06bf76ee7cc

@jankurianski I did a quick test with the above commit and things were working on. Happy if I push that to `master`? Wasn't sure what your plan was or if you were still having problems.

**Comment by jankurianski** [comment]
@amaitland Yes, please do push! :+1: 

I am still having problems, and I think it was because I foolishly updated the package version via editing the `.csproj` files in a text edit - because I notice I do not have any time stamp changes in my diffs.

**Comment by jankurianski** [comment]
> What version of VS are you using? If it's VS2015 do you also have VS2013 installed?

I tried `VS2012` and `VS2013` but they both failed to build.  I think it was due to my poor package updating process.  I will stick to the GUI next time.

**Comment by amaitland** [comment]
I've updated `master`, should be ready to go.

**Comment by jankurianski** [comment]
Thanks for that.  I checked the 3 example projects in `x86` and `x64` mode and they are working fine with the new version.

**Comment by amaitland** [comment]
@jankurianski Are you happy to delete the older `2357` packages?

**Comment by jankurianski** [comment]
Yep, I just deleted the older versions.

**Comment by amaitland** [comment]
Thanks :+1: 

I went to repackage `3.2454.1301.g9e0d84d` today, just to take it for a spin, see what changes we were in for as the `2454` branch should stabilize sometime soon. Build failed for `VS2012`, looks like the code is using some new language key words, so we'll have to drop support for `VS2012`. `Chromium` it's self requires `VS2013` as a minimum I believe, so I don't see this as being a big deal. 

Really just an `FYI`, was thinking we'll support `VS2013` and `VS2015` for the `2454` branch.

**Comment by jankurianski** [comment]
Fair enough, thanks for keeping us in the loop.
