### ISSUE TITLE
Build hangs during build.

### ISSUE THREAD

**Issue by BumpkinRich** [cefsharp/cef-binary#36]
When trying to build Cef from source - https://github.com/cefsharp/cef-binary/wiki/Building-Cef-from-source the process hangs at the following 

[997/15614] RULE Generating C++ and Py...e from proto\layer_tree_settings.proto

**Comment by amaitland** [comment]
Check https://bitbucket.org/chromiumembedded/cef/wiki/BranchesAndBuilding.md to confirm that you have the relevant build requirements.

http://magpcss.org/ceforum/ is the place to ask questions about building `CEF`.
