### ISSUE TITLE
Question - Download ffmpegsumo.dll

### ISSUE THREAD

**Issue by Martin-Andersen** [cefsharp/cef-binary#43]
Hi Where can I download the correct version of ffmpegsumo.dll?

**Comment by amaitland** [comment]
> Please only open an issue if you have a BUG to report, if you simply have a question or require some assistance keep reading for info. If you do have a BUG to report, please use the Bug Report template below.

Please take the time to read the issue template, if you have a question, ask it on `Gitter`, post on `StackOverflow` or use http://magpcss.org/ceforum/ (for questions specific to `CEF`).

https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

**Comment by amaitland** [comment]
If you did some searching you'd find ffmpeg is statically compiled. 

Issue tracker for bug reports only please.

**Comment by Martin-Andersen** [comment]
Thanks - I always start with a Google search. And I found many versions of ffmpeg.
Didn't now that it was statically compiled

**Comment by amaitland** [comment]
Use the Github search above next time. Thank you!

**Comment by amaitland** [comment]
The main CefSharp project will have the relevant information, search there.

**Comment by amaitland** [comment]
https://codereview.chromium.org/1141703002
