### ISSUE TITLE
Error building nupkg

### ISSUE THREAD

**Issue by ray007** [cefsharp/cef-binary#49]
After finally managing to build my own CEF packages, I wanted to have CEF nuget packages.
Unfortunately:
```
$ powershell .\build.ps1 nupkg-only

Building nuget package

Attempting to build package from 'cef.redist.nuspec'.
Successfully created package 'nuget\cef.redist.x86.3.2987.1601.nupkg'.
Attempting to build package from 'cef.redist.nuspec'.
Successfully created package 'nuget\cef.redist.x64.3.2987.1601.nupkg'.
Attempting to build package from 'cef.sdk.nuspec'.
Could not find a part of the path 'J:\cef-binary\CEF'.
```
If I create an empty directory `CEF` of a junctions pointing to a `cef` directory within my cef/chromium checkouts, building packages here works, but building `CefSharp` with them fails.
What should `CEF` be?

**Comment by ray007** [comment]
Update: this is a problem when calling with parameter `nupkg-only`.
Calling without parameters worked without error.
Running with parameter `vs2013` now...

**Comment by japj** [comment]
Is this still an issue? I think vs2013 will just build binaries and nupkg-only will just package whatever was build previously

**Comment by ray007** [comment]
I managed to make things work, so it's currently not an issue for me anymore.

**Comment by japj** [comment]
Ok, then this issue can be closed?
