### ISSUE TITLE
Build with VC2015++ redistributable

### ISSUE THREAD

**Issue by perlun** [cefsharp/cef-binary#64]
At some point, this should be done. This issue exists to remind us about this fact.

As @amaitland pointed out, the immediate effect is that the number of support requests will increase. We will have to factor this into the equation: unless we are ready and willing to accept this, it should be postponed until a more suitable time.

I _think_ that perhaps CefSharp 63 or 64 would be an appropriate time to do this.

**Comment by amaitland** [comment]
`master` has been upgraded to build `VS2015` and `VS2017` packages.
