### ISSUE TITLE
Error trying to upgrade to cef.redist.x64 from 3.2987.1601 to 3.3239.1716

### ISSUE THREAD

**Issue by xantari** [cefsharp/cef-binary#66]
**Error Observed:**
Unable to resolve dependencies. 'cef.redist.x64 3.3239.1716' is not compatible with 'CefSharp.Common 57.0.0 constraint: cef.redist.x64 (= 3.2987.1601)'.	

There is no newer version of CefSharp.Common available on Nuget.

Did someone update these packages but forget to update CefSharp.Common nuget package as well?

Same issue with cef.redist.x86

**Comment by amaitland** [comment]
> Did someone update these packages but forget to update CefSharp.Common nuget package as well?

`2987` is the `57` branch of `Chromium, and `3239` is the `63` branch, you cannot mix and match `cef.redist` packages.

> There is no newer version of CefSharp.Common available on Nuget.

See https://www.nuget.org/packages/CefSharp.Common/63.0.0-pre01
