### ISSUE TITLE
Request to Update to 3.3325 version

### ISSUE THREAD

**Issue by matab2004** [cefsharp/cef-binary#69]
Is it possible to upgrade cef sdk to 3.3325 or latest to sync with x86 redist version?
I am getting geolocation entry point is not found in libcef.dll in my c++ application if I use the latest x86 version. Because I used 3.3239.1723 lib version to link my c++ application. Please help Thank you in Advance

**Comment by amaitland** [comment]
You can download newer packages from https://www.myget.org/gallery/cefsharp or build them yourself. 

CEF has removed the geolocation API, so upgrading to a newer version won't help you
