### ISSUE TITLE
build.ps1 - Update to support new CEF format

### ISSUE THREAD

**Issue by amaitland** [cefsharp/cef-binary#76]
https://bitbucket.org/chromiumembedded/cef/issues/2596/improve-cef-version-number-format

**Comment by amaitland** [comment]
First builds using the new format are up on http://opensource.spotify.com/cefbuilds/index.html

**Comment by amaitland** [comment]
https://magpcss.org/ceforum/viewtopic.php?f=6&t=16636

**Comment by merceyz** [comment]
Encoding issue has been fixed
https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=16633&p=41278#p41285

**Comment by amaitland** [comment]
@mitchcapper Not sure if this will cause problems with your `Docker` scripts, let me know if you require any additional changes.

- Old version number format `3.3683.1920`
- New version number format `73.1.12`

The `CefSharp` package version numbers will change as well, see https://github.com/cefsharp/CefSharp/issues/2706
