### ISSUE TITLE
Support for Linux and mac with GTK 

### ISSUE THREAD

**Issue by danielmeza** [cefsharp/cef-binary#79]
The goal of this is to include support for Linux and Mac now that .net core run in there, we can use GTK as a UI Framework for now.

**Comment by amaitland** [comment]
There are no plans to package CEF as part of this project for Linux or macOS. 
Microsoft have confirmed they have no plans to port VC++ to other operating systems. 

See https://devblogs.microsoft.com/cppblog/the-future-of-cpp-cli-and-dotnet-core-3/
