### ISSUE TITLE
Support audio/video or not?

### ISSUE THREAD

**Issue by winsoft666** [cefsharp/cef-binary#85]
I download package form https://www.nuget.org/packages/cef.redist.x86

Whether this package support play audio/video or not?

**Comment by amaitland** [comment]
It's a repackaged version of the official CEF builds from http://opensource.spotify.com/cefbuilds/index.html

**Comment by amaitland** [comment]
Freely available audio/video codecs are supported. H264/AAC are not supported.

**Comment by winsoft666** [comment]
official CEF builds don't support audio/video.
