### ISSUE TITLE
Add license to cef.redist

### ISSUE THREAD

**Issue by jozefizso** [cefsharp/cef-binary#87]
- **What version of the product are you using?**
    - What version are you using? **Nuget**
	- Version: **86.0.241**

- **What architecture x86 or x64?**
    x86 & x64
    
- **On what operating system?**
   Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
    
- **What steps will reproduce the problem?**
    1. Create new Win Forms project in Visual Studio
    2. Add the **CefSharp.WinForms** nuget package to the project
    3. Configure the project to either x86 or x64 platform
    4. Build the project.

- **What is the expected output? What do you see instead?**

The **README.txt** file in the build output is provided by the **cef.redist** packages. The license section states `The CEF project is BSD licensed. Please read the LICENSE.txt file included with
this binary distribution for licensing terms and conditions.`

There is not **LICENSE.txt** provided in the nuget packages nor in the build output with CefSharp and Chromium binaries.

CefSharp nuget packages should include the **LICENSE.txt** file so it can be distributed with binaries.

**Comment by amaitland** [comment]
The Nuget package references the license https://github.com/cefsharp/cef-binary/blob/master/NuGet/cef.redist.nuspec#L10

Are you saying you'd like this text file include? You are welcome to submit a PR.

**Comment by amaitland** [comment]
`License.txt` from the `CEF ` binary distribution was added in https://github.com/cefsharp/cef-binary/commit/538a0d4a20af5969df0239129b1a925ac161a4ef

Version `88` should include the license that comes directly from `CEF` package.
