### ISSUE TITLE
Cef sharp x64, x86 cef redist update error

### ISSUE THREAD

**Issue by jarno9981** [cefsharp/cef-binary#89]
![20210109_101329](https://user-images.githubusercontent.com/53493418/104087924-697d6e80-5263-11eb-9be8-2fc34a030221.jpg)

**Comment by amaitland** [comment]
Don't upgrade `cef.redist.x64/cef.redist.x86` manually, just upgrade the main `CefSharp.WinForms/Wpf/OffScreen` packages.

**Comment by amaitland** [comment]
If you wish to try out a `-pre` release of version `87` I've just uploaded one.

- https://www.nuget.org/packages/CefSharp.WinForms/87.1.130-pre
- https://www.nuget.org/packages/CefSharp.Wpf/87.1.130-pre
- https://www.nuget.org/packages/CefSharp.OffScreen/87.1.130-pre

**Comment by jarno9981** [comment]
Already using it, how auto change url in textbox


Op za 9 jan. 2021 11:11 schreef Alex Maitland <notifications@github.com>:

**Comment by amaitland** [comment]
If you have a question then please use one of the 
https://github.com/cefsharp/CefSharp/discussions
https://stackoverflow.com/questions/tagged/cefsharp
