### ISSUE TITLE
How to use cef.sdk.mp4support?

### ISSUE THREAD

**Issue by serjou1** [cefsharp/cef-binary#92]
I forked CefSharp repo but I can't install `cef.sdk.mp4support` to `CefSharp.Core` I get error:
`Could not install package 'cef.sdk.mp4support 79.0.0'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

I also tried to build own cef with codecs enabled but it fails all the time with out of memory exception (32GB RAM + 50GB swap)

**Comment by amaitland** [comment]
> How to use cef.sdk.mp4support?

The package author failed to update the project url/description, that was created by someone else and is an unofficial/unsupported package. I've never seen it before.

It only includes version `79` which is very old and unsupported. 

> I forked CefSharp repo but I can't install `cef.sdk.mp4support` to `CefSharp.Core` I get error:

You can manually edit the `vcxproj` file and the `packages.config` file for `CefSharp.Core` and `CefSharp.BrowserSubProcess.Core`, that's probably the easiest option.

> I also tried to build own cef with codecs enabled but it fails all the time with out of memory exception (32GB RAM + 50GB swap)

That is outside the scope of this project. Personally I rarely compile `CEF` from source.

If you need help with this then https://www.magpcss.org/ceforum/viewforum.php?f=6 is the place to ask.

There is a fairly recent existing conversation on the topic at https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=13515 which is likely helpful (there are multiple pages, you might be best to start from the end and work your way back).
